import tkinter as tk
from tkinter import ttk
from tkinter import scrolledtext

def analyze_text_action():
#--- ЗАБИРАЄМО ТЕКСТ КОРИСТУВАЧА ТА ПЕРЕДАЄМО МОДЕЛІ ---

    # 1. Забираємо текст, який ввів користувач
    user_text = text_input.get("1.0", tk.END).strip()
    
    if not user_text:
        result_label.config(text="❌ Please enter the text to be analyzed!", foreground="#ff5555")
        return
    

    # --- ТИМЧАСОВА ЗАГЛУШКА (поки немає моделі) ---
    dummy_percentage = 50.0
    
    # 2. Виводимо вердикт на екран
    color = None

    if  65 < dummy_percentage <= 100: 
        color ="#ff5555"
    elif 35 < dummy_percentage <= 65:
        color ="#deff08"
    else:
        color = "#05f234"

    result_label.config(
        text= f"This text was generated by AI with a probability of {dummy_percentage}%", 
        foreground = color
       
    )
    
    # Оновлюємо додаткові метрики внизу
    metrics_label.config(
        text="Metrics:\n"
             "• Average lenght of sentence: 18.4 words\n"
             "• TTR score (language richness): 0.42 (Low)\n"
             "• Parts of speech: Nouns 14%, Verbs 22%"
    )

#--- ДИЗАЙН ВІКНА ---
root = tk.Tk()
root.title("AI-detector 3000")
root.geometry("700x550")
root.configure(bg="#1e1e2e") # Темно-синій/чорний фон (Сучасний вайб)

# Налаштування стилів для стандартних елементів
style = ttk.Style()
style.theme_use('default')
style.configure("TLabel", background="#1e1e2e", foreground="#cdd6f4", font=("Arial", 11))
style.configure("TButton", background="#45475a", foreground="#ffffff", font=("Arial", 11, "bold"), borderwidth=0)
style.map("TButton", background=[("active", "#585b70")])

# 1. Заголовок програми
title_label = ttk.Label(
    root, 
    text="🔍 AI-detector 3000", 
    font=("Arial", 18, "bold"), 
    foreground="#cba6f7" # Фіолетовий акцент
)
title_label.pack(pady=15)

# 2. Підзаголовок (Слоган)
subtitle_label = ttk.Label(
    root, 
    text="Paste the text below to check if it has a human soul:",
    font=("Arial", 10, "italic")
)
subtitle_label.pack(pady=5)

# 3. Поле для вводу тексту (із прокруткою)
text_input = scrolledtext.ScrolledText(
    root, 
    wrap=tk.WORD, 
    width=75, 
    height=12, 
    font=("Arial", 11),
    bg="#313244", 
    fg="#cdd6f4", 
    insertbackground="white", # Колір курсору
    bd=0, 
    highlightthickness=1, 
    highlightbackground="#45475a"
)
text_input.pack(pady=15, padx=20)

# 4. Кнопка аналізу
analyze_button = ttk.Button(
    root, 
    text="Check text", 
    command=analyze_text_action, # При натисканні викличеться функція вище
    cursor="hand2"
)
analyze_button.pack(pady=10, ipady=5, ipadx=10)

# 5. Рамка для виводу результатів (Картка)
result_card = tk.Frame(root, bg="#313244", bd=0, highlightthickness=1, highlightbackground="#45475a")
result_card.pack(fill=tk.BOTH, expand=True, padx=20, pady=15)

# Головний вердикт всередині картки
result_label = ttk.Label(
    result_card, 
    text="Waiting for the text to be analyzed...", 
    font=("Arial", 13, "bold"), 
    background="#313244", 
    foreground="#a6adc8"
)
result_label.pack(pady=10, padx=10)

# Детальні метрики всередині картки
metrics_label = ttk.Label(
    result_card, 
    text="The metrics will appear after scanning", 
    font=("Arial", 10), 
    background="#313244", 
    foreground="#bac2de",
    justify=tk.LEFT
)
metrics_label.pack(pady=5, padx=10, anchor="w")

# Запуск головного циклу програми
root.mainloop()
